from .animals import Animal
from .copperhead import Copperhead
from .diamondback import Diamondback
from .donkey import Donkey
from .fish_with_no_eyes import Fish_With_No_Eyes
from .goat import Goat
from .goldfish import Goldfish
from .gorgon import Gorgon
from .jellyfish import Jellyfish
from .llama import Llama
from .mallard import Mallard
from .orangutan import Orangutan
from .rat_snake import Rat_Snake
from .rattlesnake import Rattlesnake
from .shark import Shark
from .small_horse import Small_Horse